import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: [".wxt/", ".output/", "dist/", "node_modules/"],
  },
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        browser: "readonly",
        chrome: "readonly",
        window: "readonly",
        document: "readonly",
        console: "readonly",
        navigator: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        HTMLElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLInputElement: "readonly",
        Element: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        Range: "readonly",
        Selection: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        Event: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        DOMRect: "readonly",
        Text: "readonly",
        TreeWalker: "readonly",
        NodeFilter: "readonly",
        getComputedStyle: "readonly",
        fetch: "readonly",
        URL: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        ReadableStream: "readonly",
        AbortController: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        queueMicrotask: "readonly",
        structuredClone: "readonly",
        performance: "readonly",
        self: "readonly",
        globalThis: "readonly",
        Worker: "readonly",
        postMessage: "readonly",
        onmessage: "readonly",
        indexedDB: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        caches: "readonly",
        crypto: "readonly",
        CSS: "readonly",
        CustomEvent: "readonly",
        PointerEvent: "readonly",
        FocusEvent: "readonly",
        ClipboardEvent: "readonly",
        InputEvent: "readonly",
        matchMedia: "readonly",
        location: "readonly",
        history: "readonly",
        screen: "readonly",
        scrollTo: "readonly",
        scrollBy: "readonly",
        getSelection: "readonly",
        addEventListener: "readonly",
        removeEventListener: "readonly",
        dispatchEvent: "readonly",
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "off",
      "no-console": "off",
    },
  },
);
